version: 0.2
run-as: root


phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - aws --version
      - npm build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp --recursive ./aws_code_pipeline/ s3://avi-demo-static-site
      
