version: 0.2
run-as: root


phases:
  install:
    runtime-versions:
      nodejs: 30
  pre_build:
    commands:
      - echo Installing
      - npm install
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - CI=true npm test
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://avi-demo-static-site --acl public-read
